In [1]:
import numpy as np

# Sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of the sigmoid function
def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

def SSE(y, x):
    #sum of the squared errors (SSE)
    return 0.5*np.sum((y - x)**2)

In [2]:
y = np.array([0.3])

inputs = np.array([2,4,5])


### Weights
We want these to be small such that the input to the sigmoid is in the linear region near 0 and not squashed at the high and low ends. It's also important to initialize them randomly so that they all have different starting values and diverge, breaking symmetry. So, we'll initialize the weights from a normal distribution centered at 0. A good value for the scale is 1/√n where n is the number of input units. This keeps the input to the sigmoid low for increasing numbers of input units.

In [3]:
weights = np.random.normal(scale=1/3**.5, size=3)
bias = np.random.normal(scale=1/3**.5, size=1)
print(weights)

[ 0.41253835 -0.5639937   0.09712351]


In [4]:
del_w = 0
last_loss = None

# Neural Network hyperparameters
epochs = 1000
learnrate = 0.00001

In [5]:
for e in range(epochs):
    mat_mult = np.dot(inputs, np.transpose(weights)) + bias
#     print(mat_mult)
    output = sigmoid(mat_mult)
#     print('sigmoid', output)
    error_term = (y - output)*sigmoid_prime(mat_mult)
    del_w = del_w + error_term*inputs
#     print(del_w)
    weights += learnrate*del_w
    
    error = SSE(y, output)
    
    if e % 10 == 0:
        print(e, error)
    if last_loss and last_loss < error:
        print('last error:', e, error)
        break
    else:
        last_loss = error

0 0.00083065007726
10 0.00082913460413
20 0.000824872633275
30 0.000817889586203
40 0.000808227188924
50 0.000795943329843
60 0.000781111860145
70 0.000763822334949
80 0.000744179693107
90 0.000722303873152
100 0.000698329362585
110 0.000672404677466
120 0.000644691769102
130 0.000615365354585
140 0.000584612167948
150 0.000552630128887
160 0.000519627426254
170 0.000485821513946
180 0.000451438017377
190 0.000416709549375
200 0.000381874435238
210 0.000347175347638
220 0.000312857853225
230 0.000279168874045
240 0.000246355068342
250 0.000214661136811
260 0.000184328062062
270 0.000155591290758
280 0.000128678869684
290 0.000103809548862
300 8.11908665844e-05
310 6.10172330558e-05
320 4.34680310023e-05
330 2.87057531473e-05
340 1.68741978423e-05
350 8.09674527571e-06
360 2.47473755836e-06
370 8.59865338551e-08
last error: 373 8.43270624347e-09


In [6]:
error

8.4327062434678175e-09

In [7]:
weights


array([ 0.42160957, -0.54585125,  0.11980157])

In [8]:
output

array([ 0.30012987])